apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.general.name }}
  namespace: {{ .Values.general.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Values.general.name }}
            port:
              number: 8080
