apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.general.name }}
  name: {{ .Values.general.name }}
  namespace: {{ .Values.general.namespace }}
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.general.name }}
  type: ClusterIP
status:
  loadBalancer: {}
