apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  labels:
    name: demo
spec:
  project: default
  sources:
    - repoURL: https://github.com/mwocka/dev_opole.git
      targetRevision: main
      path: demo_1/application_manifests
      ref: main

  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
